[build]
# Pick ONE of these compilation targets
 target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+

[target.thumbv6m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
runner = 'probe-rs run --chip rp2040' # <- change for your chip


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"